# Generated by Django 2.1.1 on 2018-09-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='thumbnail',
            new_name='thumb',
        ),
    ]
